Repository HackrackClub/BookMyShow-Clone, pull requests merged in 2021-10, with the labels that each got.

#3 created a file named contributors.md
  CONTRIBUTING.md
Labels: hactoberfest-accepted

#7 Update CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: more changes needed

#18 Logo Update (White Text with Red box in middle)
  public/bmslogo.png
  public/mainlogo.png
  src/components/Navbar/bmslogo.png
  src/components/Navbar/mainlogo.png
Labels: Approval-Needed
